### ISSUE TITLE
Bug in economic model computation of hospitalisations

### ISSUE THREAD

**Issue by stur86** [ptti/ptti#1]
In the economic model, hospitalisations are calculated as:

    Medical_Outcomes['Hospital_Cases'] = In_Hospital_Deaths / (ICU_Pct*ICU_Fatality) + ((1-ICU_Pct) * Non_ICU_Fatality)

This seems a mistake, as the last part is just a constant probability that gets summed to the rest. It's probably supposed to be

    Medical_Outcomes['Hospital_Cases'] = In_Hospital_Deaths / (ICU_Pct*ICU_Fatality + (1-ICU_Pct) * Non_ICU_Fatality)

**Comment by davidmanheim** [comment]
Now fixed in # 92148abd6592e2a6ed27ab6664cf3a185540a5df
